version: '3.7'
services:
    jenkins:
        build:
            context: ./
        user: root
        volumes:
            - ${HOST_DOCKER}:/var/run/docker.sock
            - ${HOST_JENKINS_DATA}:/var/jenkins_home
        ports:
            - "${HOST_WWW}:8180"
            - "${HOST_OTHER}:50000"
        environment:
            JENKINS_OPTS: --httpPort=${HOST_WWW}