version: '3.7'
services:
    jenkins:
        build:
            context: ./
        user: root
        volumes:
            - ${HOST_DOCKER_SOCKET}:${CONTAINER_DOCKER_SOCKET}
            - ${HOST_JENKINS_DATA}:${CONTAINER_JENKINS_DATA}
        ports:
            - "${HOST_PORT_WWW}:${CONTAINER_PORT_WWW}"
            - "${HOST_PORT_OTHER}:${CONTAINER_PORT_OTHER}"
        environment:
            JENKINS_OPTS: --httpPort=${CONTAINER_PORT_WWW}